### ISSUE TITLE
Plugin problem

### ISSUE THREAD

**Issue by peters59** [PAlexcom/PHPStructuredData#3]
if I render the following html, the 2. display($parms) call for data-sd="organizer.Person" returns an empty string. Any idea?
&lt;div class="boxcontent" data-sd="SportsEvent"&gt;
  &lt;span data-sd="location.Place"> 
       &lt;div class="factsright" data-sd="address.PostalAddress""&gt;
          .... 
       &lt;/div&gt;
  &lt;/span&gt;
  &lt;a data-sd="url"&gt;blabla&lt;/a&gt;
  &lt;div class="test" data-sd="organizer.Person"&gt; ...  &lt;/div&gt;
&lt;/div&gt;

If I remove "<span data-sd="location.Place"> .... </span>" it works.

it looks as if the div structure does not correspond to the schema structure
if I, change,
  &lt;a data-sd="url"&gt;blah &lt;/a&gt;
to
  &lt;a data-sd="Event url"&gt; blah &lt;/a&gt;

it works! because the schema is switched back to "Event"

**Comment by PAlexcom** [comment]
@peters59 thanks for the report
> If I remove " .... " it works.

Could you provide an complete example of how do you use the semantics and the output you are expecting please? (or link to your code somewhere) From the example you've provided I can't understand where is the problem.
By the way you are using `"address.PostalAddress""` at the end with two quotes.

> it works! because the schema is switched back to "Event"

Yes in some cases you need to declare again the Type in order to switch back to the parent, take a look at this example please https://github.com/PAlexcom/PHPStructuredData#usage-example-1, the `<?php echo $scope; ?>` is declared twice as you will see.
Once the library changes the current Type to use it does not know when to change it back to the previous  type, this is the reason why you need to specify it manually.
